kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    app.openshift.io/vcs-ref: ''
    app.openshift.io/vcs-uri: 'https://github.com/openshift-instruqt/blog-django-py.git'
    deployment.kubernetes.io/revision: '2'
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"blog-django-py-git:latest","namespace":"fiap341865"},"fieldPath":"spec.template.spec.containers[?(@.name==\"blog-django-py-git\")].image","pause":"false"}]
    openshift.io/generated-by: OpenShiftWebConsole
  selfLink: /apis/apps/v1/namespaces/fiap341865/deployments/blog-django-py-git
  resourceVersion: '13513878'
  name: blog-django-py-git
  uid: 1891032d-2eb8-472e-bd4f-b8bba20f7fea
  creationTimestamp: '2021-12-16T23:52:47Z'
  generation: 2
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: apps/v1
      time: '2021-12-16T23:52:47Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:alpha.image.policy.openshift.io/resolve-names': {}
            'f:app.openshift.io/vcs-ref': {}
            'f:app.openshift.io/vcs-uri': {}
            'f:image.openshift.io/triggers': {}
            'f:openshift.io/generated-by': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:app.kubernetes.io/component': {}
            'f:app.kubernetes.io/instance': {}
            'f:app.kubernetes.io/name': {}
            'f:app.kubernetes.io/part-of': {}
            'f:app.openshift.io/runtime': {}
            'f:app.openshift.io/runtime-version': {}
        'f:spec':
          'f:progressDeadlineSeconds': {}
          'f:replicas': {}
          'f:revisionHistoryLimit': {}
          'f:selector':
            'f:matchLabels':
              .: {}
              'f:app': {}
          'f:strategy':
            'f:rollingUpdate':
              .: {}
              'f:maxSurge': {}
              'f:maxUnavailable': {}
            'f:type': {}
          'f:template':
            'f:metadata':
              'f:labels':
                .: {}
                'f:app': {}
                'f:deploymentconfig': {}
            'f:spec':
              'f:containers':
                'k:{"name":"blog-django-py-git"}':
                  .: {}
                  'f:imagePullPolicy': {}
                  'f:name': {}
                  'f:ports':
                    .: {}
                    'k:{"containerPort":8080,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:protocol': {}
                  'f:resources': {}
                  'f:terminationMessagePath': {}
                  'f:terminationMessagePolicy': {}
              'f:dnsPolicy': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:securityContext': {}
              'f:terminationGracePeriodSeconds': {}
    - manager: openshift-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2021-12-16T23:54:15Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:template':
            'f:spec':
              'f:containers':
                'k:{"name":"blog-django-py-git"}':
                  'f:image': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2021-12-16T23:54:22Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:deployment.kubernetes.io/revision': {}
        'f:status':
          'f:availableReplicas': {}
          'f:conditions':
            .: {}
            'k:{"type":"Available"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Progressing"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:observedGeneration': {}
          'f:readyReplicas': {}
          'f:replicas': {}
          'f:updatedReplicas': {}
  namespace: fiap341865
  labels:
    app: blog-django-py-git
    app.kubernetes.io/component: blog-django-py-git
    app.kubernetes.io/instance: blog-django-py-git
    app.kubernetes.io/name: python
    app.kubernetes.io/part-of: blog-django-py-app
    app.openshift.io/runtime: python
    app.openshift.io/runtime-version: latest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-django-py-git
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: blog-django-py-git
        deploymentconfig: blog-django-py-git
    spec:
      containers:
        - name: blog-django-py-git
          image: >-
            image-registry.openshift-image-registry.svc:5000/fiap341865/blog-django-py-git:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 2
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2021-12-16T23:54:22Z'
      lastTransitionTime: '2021-12-16T23:54:22Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2021-12-16T23:54:22Z'
      lastTransitionTime: '2021-12-16T23:52:47Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "blog-django-py-git-6b6799485b" has successfully progressed.
--- 
 kind: Build
apiVersion: build.openshift.io/v1
metadata:
  annotations:
    openshift.io/build-config.name: blog-django-py-git
    openshift.io/build.number: '1'
    openshift.io/build.pod-name: blog-django-py-git-1-build
  selfLink: /apis/build.openshift.io/v1/namespaces/fiap341865/builds/blog-django-py-git-1
  resourceVersion: '13513792'
  name: blog-django-py-git-1
  uid: 9d68f797-7649-4992-a807-3f32649277a6
  creationTimestamp: '2021-12-16T23:52:47Z'
  namespace: fiap341865
  ownerReferences:
    - apiVersion: build.openshift.io/v1
      kind: BuildConfig
      name: blog-django-py-git
      uid: c22883e4-a614-4bec-ad20-5f81ceae3b87
      controller: true
  labels:
    app: blog-django-py-git
    app.kubernetes.io/part-of: blog-django-py-app
    app.kubernetes.io/instance: blog-django-py-git
    openshift.io/build-config.name: blog-django-py-git
    app.kubernetes.io/component: blog-django-py-git
    openshift.io/build.start-policy: Serial
    buildconfig: blog-django-py-git
    app.openshift.io/runtime: python
    app.kubernetes.io/name: python
    app.openshift.io/runtime-version: latest
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'blog-django-py-git:latest'
    pushSecret:
      name: builder-dockercfg-l9j6x
  resources: {}
  triggeredBy:
    - message: Image change
      imageChangeBuild:
        imageID: >-
          image-registry.openshift-image-registry.svc:5000/openshift/python@sha256:09ccc9a03f554b96c843832baa8eee02fe8794e9fab6b9189b789e21d2e0332a
        fromRef:
          kind: ImageStreamTag
          namespace: openshift
          name: 'python:latest'
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: DockerImage
        name: >-
          image-registry.openshift-image-registry.svc:5000/openshift/python@sha256:09ccc9a03f554b96c843832baa8eee02fe8794e9fab6b9189b789e21d2e0332a
      pullSecret:
        name: builder-dockercfg-l9j6x
  postCommit: {}
  serviceAccount: builder
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift-instruqt/blog-django-py.git'
    contextDir: /
  revision:
    type: Git
    git:
      commit: 9c4f338ab5f3a5ae379ecaa5bcc7d449fa41648e
      author:
        name: ryan jarvinen
        email: ryan.jarvinen@gmail.com
      committer:
        name: GitHub
        email: noreply@github.com
      message: 'Merge pull request #9 from mixpix3ls/master'
status:
  output:
    to:
      imageDigest: 'sha256:ab9b441d6788af259a36dc70f6a2cbc3701149441628cbb81a1e8e622fec487c'
  config:
    kind: BuildConfig
    namespace: fiap341865
    name: blog-django-py-git
  outputDockerImageReference: >-
    image-registry.openshift-image-registry.svc:5000/fiap341865/blog-django-py-git:latest
  duration: 89000000000
  startTimestamp: '2021-12-16T23:52:47Z'
  stages:
    - name: FetchInputs
      startTime: '2021-12-16T23:52:51Z'
      durationMilliseconds: 468
      steps:
        - name: FetchGitSource
          startTime: '2021-12-16T23:52:51Z'
          durationMilliseconds: 468
    - name: PullImages
      startTime: '2021-12-16T23:52:54Z'
      durationMilliseconds: 29517
      steps:
        - name: PullBaseImage
          startTime: '2021-12-16T23:52:54Z'
          durationMilliseconds: 29517
    - name: Build
      startTime: '2021-12-16T23:53:23Z'
      durationMilliseconds: 50690
      steps:
        - name: DockerBuild
          startTime: '2021-12-16T23:53:23Z'
          durationMilliseconds: 50690
    - name: PushImage
      startTime: '2021-12-16T23:54:14Z'
      durationMilliseconds: 1107
      steps:
        - name: PushImage
          startTime: '2021-12-16T23:54:14Z'
          durationMilliseconds: 1107
  conditions:
    - type: New
      status: 'False'
      lastUpdateTime: '2021-12-16T23:52:47Z'
      lastTransitionTime: '2021-12-16T23:52:47Z'
    - type: Pending
      status: 'False'
      lastUpdateTime: '2021-12-16T23:52:52Z'
      lastTransitionTime: '2021-12-16T23:52:52Z'
    - type: Running
      status: 'False'
      lastUpdateTime: '2021-12-16T23:54:16Z'
      lastTransitionTime: '2021-12-16T23:54:16Z'
    - type: Complete
      status: 'True'
      lastUpdateTime: '2021-12-16T23:54:16Z'
      lastTransitionTime: '2021-12-16T23:54:16Z'
  completionTimestamp: '2021-12-16T23:54:16Z'
  phase: Complete
