kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    app.openshift.io/vcs-ref: ''
    app.openshift.io/vcs-uri: 'https://github.com/openshift-katacoda/blog-django-py.git'
    deployment.kubernetes.io/revision: '2'
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"blog-django-py:latest","namespace":"fiap-341865"},"fieldPath":"spec.template.spec.containers[?(@.name==\"blog-django-py\")].image","pause":"false"}]
    openshift.io/generated-by: OpenShiftWebConsole
  selfLink: /apis/apps/v1/namespaces/new/deployments/blog-django-py
  name: blog-django-py

labels:
   # list of labels that are applied to every object during the template to config transformation
  template: blog-django-py

parameters:

- name: blog-django-py
  description: The name of the application
  value: dashboard
- name: dashboard_blog
  description: The title of the dashboard
  value: blog-django-py dashboard
- name: blog-django-py-git-fiap-341865.apps.na46.prod.nextcle.com
  description: The DNS to use for the route
  value: blog-django-py-git-fiap-341865

objects:

# creates a specific service account for running the application
# so that you can give it special rights to view other projects.
- kind: ServiceAccount
  apiVersion: v1
  metadata:
    name: dashboard

# defines a wrapper on top of our newly built image
# (this is used to trigger a deployment if the image changes = has been rebuilt)
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: blog-django-py
    labels:
      application: blog-django-py

# defines the build configuration (using the Docker strategy)
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: blog-django-py
    labels:
      application: blog-django-py
  spec:
    strategy:
      type: Docker
      dockerStrategy:
        # the base image referenced by the Dockerfile
        from:
          kind: DockerImage
          name: openshift/origin-base
    source:
      type: Git
      git:
        uri: https://github.com/openshift-instruqt/blog-django-py.git
    output:
      to:
        kind: ImageStreamTag
        name: blog-django-py:latest
    triggers:
    - type: ImageChange

# defines the deployment configuration
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: blog-django-py
    labels:
      application: blog-django-py
  spec:
    replicas: 1
    selector:
      deploymentconfig: blog-django-py
    strategy:
      type: Rolling
      rollingParams:
        intervalSeconds: 1
        timeoutSeconds: 60
        updatePeriodSeconds: 1
    template:
      metadata:
        name: blog-django-py
        labels:
          deploymentconfig: blog-django-py
          application: blog-django-py
      spec:
        # this is our custom service account, that might have more rights
        serviceAccount: dashboard
        containers:
        - name: blog-django-py
          image: blog-django-py:latest
          # app config through env variables
          env:
          - name: dashboard_blog
            value: dashboard
          - name: PORT
            value: "8080"
          - name: GO_ENV
            value: prod # use "dev" if you want to disable caching
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 10
    triggers:
    # causes a new deployment to be created any time the replication controller template changes
    - type: ConfigChange
    # causes a new deployment to be created each time a new version of the image is available
    - type: ImageChange
      imageChangeParams:
        automatic: true
        from:
          kind: ImageStreamTag
          name: blog-django-py:latest
        containerNames:
        - blog-django-py
  status: {}

- kind: Service
  apiVersion: v1
  metadata:
    name: blog-django-py
    labels:
      application: blog-django-py
  spec:
    selector:
      deploymentconfig: blog-django-py
    ports:
    - port: 8080

- kind: Route
  apiVersion: v1
  metadata:
    name: blog-django-py
    labels:
      application: blog-django-py
  spec:
    host: blog-django-py-git-fiap-341865.apps.na46.prod.nextcle.com
    to:
      kind: Service
      name: blog-django-py
