kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    app.openshift.io/vcs-ref: ''
    app.openshift.io/vcs-uri: 'https://github.com/openshift-katacoda/blog-django-py.git'
    deployment.kubernetes.io/revision: '2'
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"blog-django-py:latest","namespace":"fiap-341865"},"fieldPath":"spec.template.spec.containers[?(@.name==\"blog-django-py\")].image","pause":"false"}]
    openshift.io/generated-by: OpenShiftWebConsole
  selfLink: /apis/apps/v1/namespaces/new/deployments/blog-django-py
  resourceVersion: '6631556'
  name: blog-django-py
  uid: d37dc532-577c-42ed-acab-8a78b785070f
  creationTimestamp: '2021-12-10T00:57:45Z'
  generation: 2
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: apps/v1
      time: '2021-12-10T00:57:45Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:alpha.image.policy.openshift.io/resolve-names': {}
            'f:app.openshift.io/vcs-ref': {}
            'f:app.openshift.io/vcs-uri': {}
            'f:image.openshift.io/triggers': {}
            'f:openshift.io/generated-by': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:app.kubernetes.io/component': {}
            'f:app.kubernetes.io/instance': {}
            'f:app.kubernetes.io/name': {}
            'f:app.kubernetes.io/part-of': {}
            'f:app.openshift.io/runtime': {}
            'f:app.openshift.io/runtime-version': {}
        'f:spec':
          'f:progressDeadlineSeconds': {}
          'f:replicas': {}
          'f:revisionHistoryLimit': {}
          'f:selector':
            'f:matchLabels':
              .: {}
              'f:app': {}
          'f:strategy':
            'f:rollingUpdate':
              .: {}
              'f:maxSurge': {}
              'f:maxUnavailable': {}
            'f:type': {}
          'f:template':
            'f:metadata':
              'f:labels':
                .: {}
                'f:app': {}
                'f:deploymentconfig': {}
            'f:spec':
              'f:containers':
                'k:{"name":"blog-django-py"}':
                  .: {}
                  'f:imagePullPolicy': {}
                  'f:name': {}
                  'f:ports':
                    .: {}
                    'k:{"containerPort":8080,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:protocol': {}
                  'f:resources': {}
                  'f:terminationMessagePath': {}
                  'f:terminationMessagePolicy': {}
              'f:dnsPolicy': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:securityContext': {}
              'f:terminationGracePeriodSeconds': {}
    - manager: openshift-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2021-12-10T00:59:01Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:template':
            'f:spec':
              'f:containers':
                'k:{"name":"blog-django-py"}':
                  'f:image': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2021-12-10T00:59:07Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:deployment.kubernetes.io/revision': {}
        'f:status':
          'f:availableReplicas': {}
          'f:conditions':
            .: {}
            'k:{"type":"Available"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Progressing"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:observedGeneration': {}
          'f:readyReplicas': {}
          'f:replicas': {}
          'f:updatedReplicas': {}
  namespace: new
  labels:
    app: blog-django-py
    app.kubernetes.io/component: blog-django-py
    app.kubernetes.io/instance: blog-django-py
    app.kubernetes.io/name: python
    app.kubernetes.io/part-of: blog-app
    app.openshift.io/runtime: python
    app.openshift.io/runtime-version: 3.8-ubi7
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-django-py
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: blog-django-py
        deploymentconfig: blog-django-py

parameters:

- name: blog-django-py
  description: The name of the application
  value: dashboard
- name: dashboard_blog
  description: The title of the dashboard
  value: blog-django-py dashboard
- name: blog-django-py-git-fiap-341865.apps.na46.prod.nextcle.com
  description: The DNS to use for the route
  value: blog-django-py-git-fiap-341865

objects:

# creates a specific service account for running the application
# so that you can give it special rights to view other projects.
- kind: ServiceAccount
  apiVersion: v1
  metadata:
    name: dashboard

# defines a wrapper on top of our newly built image
# (this is used to trigger a deployment if the image changes = has been rebuilt)
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: blog-django-py
    labels:
      application: blog-django-py

# defines the build configuration (using the Docker strategy)
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: blog-django-py
    labels:
      application: blog-django-py
  spec:
    strategy:
      type: Docker
      dockerStrategy:
        # the base image referenced by the Dockerfile
        from:
          kind: DockerImage
          name: openshift/origin-base
    source:
      type: Git
      git:
        uri: https://github.com/openshift-instruqt/blog-django-py.git
    output:
      to:
        kind: ImageStreamTag
        name: blog-django-py:latest
    triggers:
    - type: ImageChange

# defines the deployment configuration
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: blog-django-py
    labels:
      application: blog-django-py
  spec:
    replicas: 1
    selector:
      deploymentconfig: blog-django-py
    strategy:
      type: Rolling
      rollingParams:
        intervalSeconds: 1
        timeoutSeconds: 60
        updatePeriodSeconds: 1
    template:
      metadata:
        name: blog-django-py
        labels:
          deploymentconfig: blog-django-py
          application: blog-django-py
      spec:
        # this is our custom service account, that might have more rights
        serviceAccount: dashboard
        containers:
        - name: blog-django-py
          image: blog-django-py:latest
          # app config through env variables
          env:
          - name: dashboard_blog
            value: dashboard
          - name: PORT
            value: "8080"
          - name: GO_ENV
            value: prod # use "dev" if you want to disable caching
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 10
    triggers:
    # causes a new deployment to be created any time the replication controller template changes
    - type: ConfigChange
    # causes a new deployment to be created each time a new version of the image is available
    - type: ImageChange
      imageChangeParams:
        automatic: true
        from:
          kind: ImageStreamTag
          name: blog-django-py:latest
        containerNames:
        - blog-django-py
  status: {}

- kind: Service
  apiVersion: v1
  metadata:
    name: blog-django-py
    labels:
      application: blog-django-py
  spec:
    selector:
      deploymentconfig: blog-django-py
    ports:
    - port: 8080

- kind: Route
  apiVersion: v1
  metadata:
    name: blog-django-py
    labels:
      application: blog-django-py
  spec:
    host: blog-django-py-git-fiap-341865.apps.na46.prod.nextcle.com
    to:
      kind: Service
      name: blog-django-py
